version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: CryptoBotDB
    ports:
      - 5433:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/CryptoBotDB -baselineOnMigrate="true" -user=postgres -password=example -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - db
