--
-- PostgreSQL database dump
--

-- Dumped from database version 14.5
-- Dumped by pg_dump version 14.4

-- Started on 2022-10-05 17:25:12 +04

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE "CryptoBotDB";
--
-- TOC entry 3650 (class 1262 OID 18250)
-- Name: CryptoBotDB; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "CryptoBotDB" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'en_US.UTF-8';


ALTER DATABASE "CryptoBotDB" OWNER TO postgres;

\connect "CryptoBotDB"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 2 (class 3079 OID 18251)
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- TOC entry 3651 (class 0 OID 0)
-- Dependencies: 2
-- Name: EXTENSION "uuid-ossp"; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 210 (class 1259 OID 18262)
-- Name: balance; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.balance (
    profile_id uuid NOT NULL,
    currency_id smallint NOT NULL,
    total numeric(17,8) DEFAULT 0 NOT NULL
);


ALTER TABLE public.balance OWNER TO postgres;

--
-- TOC entry 211 (class 1259 OID 18266)
-- Name: balance_currency_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.balance_currency_id_seq
    AS smallint
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.balance_currency_id_seq OWNER TO postgres;

--
-- TOC entry 3652 (class 0 OID 0)
-- Dependencies: 211
-- Name: balance_currency_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.balance_currency_id_seq OWNED BY public.balance.currency_id;


--
-- TOC entry 212 (class 1259 OID 18267)
-- Name: currency; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.currency (
    id smallint NOT NULL,
    name character varying(20) NOT NULL
);


ALTER TABLE public.currency OWNER TO postgres;

--
-- TOC entry 213 (class 1259 OID 18270)
-- Name: currency_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.currency_id_seq
    AS smallint
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.currency_id_seq OWNER TO postgres;

--
-- TOC entry 3653 (class 0 OID 0)
-- Dependencies: 213
-- Name: currency_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.currency_id_seq OWNED BY public.currency.id;


--
-- TOC entry 214 (class 1259 OID 18271)
-- Name: currency_id_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.currency ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.currency_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 18272)
-- Name: profile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.profile (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name text NOT NULL,
    tg_user_id character varying(50) NOT NULL
);


ALTER TABLE public.profile OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 18278)
-- Name: transaction; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transaction (
    profile_id uuid NOT NULL,
    "timestamp" timestamp(0) with time zone NOT NULL,
    currency_id smallint NOT NULL,
    amount numeric(17,8) NOT NULL,
    transaction_type_id smallint NOT NULL,
    transaction_id smallint NOT NULL
);


ALTER TABLE public.transaction OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 18281)
-- Name: transaction_currency_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.transaction_currency_id_seq
    AS smallint
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.transaction_currency_id_seq OWNER TO postgres;

--
-- TOC entry 3654 (class 0 OID 0)
-- Dependencies: 217
-- Name: transaction_currency_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.transaction_currency_id_seq OWNED BY public.transaction.currency_id;


--
-- TOC entry 221 (class 1259 OID 18352)
-- Name: transaction_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transaction ALTER COLUMN transaction_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 18341)
-- Name: transaction_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transaction_type (
    id smallint NOT NULL,
    name text NOT NULL
);


ALTER TABLE public.transaction_type OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 18340)
-- Name: transaction_name_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transaction_type ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.transaction_name_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 18288)
-- Name: transaction_transaction_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.transaction_transaction_type_id_seq
    AS smallint
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.transaction_transaction_type_id_seq OWNER TO postgres;

--
-- TOC entry 3655 (class 0 OID 0)
-- Dependencies: 218
-- Name: transaction_transaction_type_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.transaction_transaction_type_id_seq OWNED BY public.transaction.transaction_type_id;


--
-- TOC entry 3465 (class 2604 OID 18290)
-- Name: balance currency_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.balance ALTER COLUMN currency_id SET DEFAULT nextval('public.balance_currency_id_seq'::regclass);


--
-- TOC entry 3633 (class 0 OID 18262)
-- Dependencies: 210
-- Data for Name: balance; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3635 (class 0 OID 18267)
-- Dependencies: 212
-- Data for Name: currency; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.currency (id, name) VALUES (1, 'USDT');
INSERT INTO public.currency (id, name) VALUES (2, 'BTC');
INSERT INTO public.currency (id, name) VALUES (3, 'ETH');
INSERT INTO public.currency (id, name) VALUES (4, 'BNB');
INSERT INTO public.currency (id, name) VALUES (5, 'SOL');
INSERT INTO public.currency (id, name) VALUES (6, 'DOGE');


--
-- TOC entry 3638 (class 0 OID 18272)
-- Dependencies: 215
-- Data for Name: profile; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3639 (class 0 OID 18278)
-- Dependencies: 216
-- Data for Name: transaction; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3643 (class 0 OID 18341)
-- Dependencies: 220
-- Data for Name: transaction_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.transaction_type (id, name) OVERRIDING SYSTEM VALUE VALUES (1, 'buy');
INSERT INTO public.transaction_type (id, name) OVERRIDING SYSTEM VALUE VALUES (2, 'sell');


--
-- TOC entry 3656 (class 0 OID 0)
-- Dependencies: 211
-- Name: balance_currency_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.balance_currency_id_seq', 1, false);


--
-- TOC entry 3657 (class 0 OID 0)
-- Dependencies: 213
-- Name: currency_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.currency_id_seq', 1, false);


--
-- TOC entry 3658 (class 0 OID 0)
-- Dependencies: 214
-- Name: currency_id_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.currency_id_seq1', 6, true);


--
-- TOC entry 3659 (class 0 OID 0)
-- Dependencies: 217
-- Name: transaction_currency_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transaction_currency_id_seq', 1, false);


--
-- TOC entry 3660 (class 0 OID 0)
-- Dependencies: 221
-- Name: transaction_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transaction_id_seq', 15, true);


--
-- TOC entry 3661 (class 0 OID 0)
-- Dependencies: 219
-- Name: transaction_name_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transaction_name_id_seq', 4, true);


--
-- TOC entry 3662 (class 0 OID 0)
-- Dependencies: 218
-- Name: transaction_transaction_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transaction_transaction_type_id_seq', 1, false);


--
-- TOC entry 3468 (class 2606 OID 18294)
-- Name: balance balance_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.balance
    ADD CONSTRAINT balance_pkey PRIMARY KEY (currency_id, profile_id);


--
-- TOC entry 3470 (class 2606 OID 18296)
-- Name: currency currency__id_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.currency
    ADD CONSTRAINT currency__id_pkey PRIMARY KEY (id);


--
-- TOC entry 3472 (class 2606 OID 18298)
-- Name: currency currency_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.currency
    ADD CONSTRAINT currency_id_key UNIQUE (id) INCLUDE (id);


--
-- TOC entry 3474 (class 2606 OID 18300)
-- Name: currency currency_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.currency
    ADD CONSTRAINT currency_name_key UNIQUE (name) INCLUDE (name);


--
-- TOC entry 3476 (class 2606 OID 18302)
-- Name: profile profile_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.profile
    ADD CONSTRAINT profile_name_key UNIQUE (name) INCLUDE (name);


--
-- TOC entry 3478 (class 2606 OID 18304)
-- Name: profile profile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.profile
    ADD CONSTRAINT profile_pkey PRIMARY KEY (id);


--
-- TOC entry 3480 (class 2606 OID 18306)
-- Name: profile profile_tg_user_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.profile
    ADD CONSTRAINT profile_tg_user_name_key UNIQUE (tg_user_id) INCLUDE (tg_user_id);


--
-- TOC entry 3484 (class 2606 OID 18347)
-- Name: transaction_type transaction_id_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction_type
    ADD CONSTRAINT transaction_id_pkey PRIMARY KEY (id);


--
-- TOC entry 3486 (class 2606 OID 18349)
-- Name: transaction_type transaction_name_id_id1_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction_type
    ADD CONSTRAINT transaction_name_id_id1_key UNIQUE (id) INCLUDE (id);


--
-- TOC entry 3488 (class 2606 OID 18351)
-- Name: transaction_type transaction_name_name_name1_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction_type
    ADD CONSTRAINT transaction_name_name_name1_key UNIQUE (name) INCLUDE (name);


--
-- TOC entry 3482 (class 2606 OID 18357)
-- Name: transaction transaction_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT transaction_pkey PRIMARY KEY (transaction_id);


--
-- TOC entry 3489 (class 2606 OID 18315)
-- Name: balance currency_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.balance
    ADD CONSTRAINT currency_id_fk FOREIGN KEY (currency_id) REFERENCES public.currency(id) NOT VALID;


--
-- TOC entry 3491 (class 2606 OID 18325)
-- Name: transaction currency_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT currency_id_fk FOREIGN KEY (currency_id) REFERENCES public.currency(id);


--
-- TOC entry 3490 (class 2606 OID 18320)
-- Name: balance profile_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.balance
    ADD CONSTRAINT profile_id_fk FOREIGN KEY (profile_id) REFERENCES public.profile(id) NOT VALID;


--
-- TOC entry 3492 (class 2606 OID 18335)
-- Name: transaction profile_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT profile_id_fk FOREIGN KEY (profile_id) REFERENCES public.profile(id);


--
-- TOC entry 3493 (class 2606 OID 18358)
-- Name: transaction transaction_type_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT transaction_type_id_fk FOREIGN KEY (transaction_type_id) REFERENCES public.transaction_type(id) NOT VALID;


-- Completed on 2022-10-05 17:25:12 +04

--
-- PostgreSQL database dump complete
--

