--
-- PostgreSQL database dump
--

-- Dumped from database version 14.5
-- Dumped by pg_dump version 14.4

-- Started on 2022-10-04 22:16:32 +04

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE "CryptoBotDB";
--
-- TOC entry 3648 (class 1262 OID 18077)
-- Name: CryptoBotDB; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "CryptoBotDB" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'en_US.UTF-8';


ALTER DATABASE "CryptoBotDB" OWNER TO postgres;

\connect "CryptoBotDB"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 2 (class 3079 OID 18078)
-- Name: uuid-ossp; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;


--
-- TOC entry 3649 (class 0 OID 0)
-- Dependencies: 2
-- Name: EXTENSION "uuid-ossp"; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION "uuid-ossp" IS 'generate universally unique identifiers (UUIDs)';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 210 (class 1259 OID 18089)
-- Name: balance; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.balance (
    profile_id uuid NOT NULL,
    currency_id smallint NOT NULL,
    total numeric(17,8) DEFAULT 0 NOT NULL
);


ALTER TABLE public.balance OWNER TO postgres;

--
-- TOC entry 211 (class 1259 OID 18093)
-- Name: balance_currency_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.balance_currency_id_seq
    AS smallint
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.balance_currency_id_seq OWNER TO postgres;

--
-- TOC entry 3650 (class 0 OID 0)
-- Dependencies: 211
-- Name: balance_currency_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.balance_currency_id_seq OWNED BY public.balance.currency_id;


--
-- TOC entry 212 (class 1259 OID 18094)
-- Name: currency; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.currency (
    id smallint NOT NULL,
    name character varying(20) NOT NULL
);


ALTER TABLE public.currency OWNER TO postgres;

--
-- TOC entry 213 (class 1259 OID 18097)
-- Name: currency_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.currency_id_seq
    AS smallint
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.currency_id_seq OWNER TO postgres;

--
-- TOC entry 3651 (class 0 OID 0)
-- Dependencies: 213
-- Name: currency_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.currency_id_seq OWNED BY public.currency.id;


--
-- TOC entry 214 (class 1259 OID 18098)
-- Name: currency_id_seq1; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.currency ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.currency_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 18099)
-- Name: profile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.profile (
    id uuid DEFAULT public.uuid_generate_v4() NOT NULL,
    name text NOT NULL,
    tg_user_id character varying(50) NOT NULL
);


ALTER TABLE public.profile OWNER TO postgres;

--
-- TOC entry 216 (class 1259 OID 18105)
-- Name: transaction; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transaction (
    profile_id uuid NOT NULL,
    "timestamp" timestamp(0) with time zone NOT NULL,
    currency_id smallint NOT NULL,
    amount numeric(17,8) NOT NULL,
    transaction_id smallint
);


ALTER TABLE public.transaction OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 18108)
-- Name: transaction_currency_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.transaction_currency_id_seq
    AS smallint
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.transaction_currency_id_seq OWNER TO postgres;

--
-- TOC entry 3652 (class 0 OID 0)
-- Dependencies: 217
-- Name: transaction_currency_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.transaction_currency_id_seq OWNED BY public.transaction.currency_id;


--
-- TOC entry 218 (class 1259 OID 18109)
-- Name: transaction_name; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transaction_name (
    id smallint NOT NULL,
    name text NOT NULL
);


ALTER TABLE public.transaction_name OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 18114)
-- Name: transaction_name_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transaction_name ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaction_name_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 18116)
-- Name: transaction_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.transaction_type_id_seq
    AS smallint
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.transaction_type_id_seq OWNER TO postgres;

--
-- TOC entry 3653 (class 0 OID 0)
-- Dependencies: 220
-- Name: transaction_type_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.transaction_type_id_seq OWNED BY public.transaction_name.id;


--
-- TOC entry 3464 (class 2604 OID 18117)
-- Name: balance currency_id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.balance ALTER COLUMN currency_id SET DEFAULT nextval('public.balance_currency_id_seq'::regclass);


--
-- TOC entry 3632 (class 0 OID 18089)
-- Dependencies: 210
-- Data for Name: balance; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3634 (class 0 OID 18094)
-- Dependencies: 212
-- Data for Name: currency; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.currency (id, name) VALUES (1, 'USDT');
INSERT INTO public.currency (id, name) VALUES (2, 'BTC');
INSERT INTO public.currency (id, name) VALUES (3, 'ETH');
INSERT INTO public.currency (id, name) VALUES (4, 'BNB');
INSERT INTO public.currency (id, name) VALUES (5, 'SOL');
INSERT INTO public.currency (id, name) VALUES (6, 'DOGE');


--
-- TOC entry 3637 (class 0 OID 18099)
-- Dependencies: 215
-- Data for Name: profile; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3638 (class 0 OID 18105)
-- Dependencies: 216
-- Data for Name: transaction; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- TOC entry 3640 (class 0 OID 18109)
-- Dependencies: 218
-- Data for Name: transaction_name; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.transaction_name (id, name) VALUES (1, 'buy');
INSERT INTO public.transaction_name (id, name) VALUES (2, 'sell');


--
-- TOC entry 3654 (class 0 OID 0)
-- Dependencies: 211
-- Name: balance_currency_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.balance_currency_id_seq', 3, true);


--
-- TOC entry 3655 (class 0 OID 0)
-- Dependencies: 213
-- Name: currency_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.currency_id_seq', 1, false);


--
-- TOC entry 3656 (class 0 OID 0)
-- Dependencies: 214
-- Name: currency_id_seq1; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.currency_id_seq1', 6, true);


--
-- TOC entry 3657 (class 0 OID 0)
-- Dependencies: 217
-- Name: transaction_currency_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transaction_currency_id_seq', 1, false);


--
-- TOC entry 3658 (class 0 OID 0)
-- Dependencies: 219
-- Name: transaction_name_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transaction_name_id_seq', 2, true);


--
-- TOC entry 3659 (class 0 OID 0)
-- Dependencies: 220
-- Name: transaction_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transaction_type_id_seq', 1, false);


--
-- TOC entry 3467 (class 2606 OID 18121)
-- Name: balance balance_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.balance
    ADD CONSTRAINT balance_pkey PRIMARY KEY (currency_id, profile_id);


--
-- TOC entry 3469 (class 2606 OID 18125)
-- Name: currency currency_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.currency
    ADD CONSTRAINT currency_id_key UNIQUE (id) INCLUDE (id);


--
-- TOC entry 3471 (class 2606 OID 18123)
-- Name: currency currency_id_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.currency
    ADD CONSTRAINT currency_id_pkey PRIMARY KEY (id);


--
-- TOC entry 3473 (class 2606 OID 18127)
-- Name: currency currency_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.currency
    ADD CONSTRAINT currency_name_key UNIQUE (name) INCLUDE (name);


--
-- TOC entry 3475 (class 2606 OID 18129)
-- Name: profile profile_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.profile
    ADD CONSTRAINT profile_name_key UNIQUE (name) INCLUDE (name);


--
-- TOC entry 3477 (class 2606 OID 18131)
-- Name: profile profile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.profile
    ADD CONSTRAINT profile_pkey PRIMARY KEY (id);


--
-- TOC entry 3479 (class 2606 OID 18133)
-- Name: profile profile_tg_user_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.profile
    ADD CONSTRAINT profile_tg_user_name_key UNIQUE (tg_user_id) INCLUDE (tg_user_id);


--
-- TOC entry 3483 (class 2606 OID 18223)
-- Name: transaction_name transaction_name_id_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction_name
    ADD CONSTRAINT transaction_name_id_pkey PRIMARY KEY (id);


--
-- TOC entry 3481 (class 2606 OID 18249)
-- Name: transaction transaction_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT transaction_pkey PRIMARY KEY (profile_id, currency_id);


--
-- TOC entry 3485 (class 2606 OID 18221)
-- Name: transaction_name transaction_type_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction_name
    ADD CONSTRAINT transaction_type_id_key UNIQUE (id) INCLUDE (id);


--
-- TOC entry 3487 (class 2606 OID 18141)
-- Name: transaction_name transaction_type_type_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction_name
    ADD CONSTRAINT transaction_type_type_key UNIQUE (name) INCLUDE (name);


--
-- TOC entry 3488 (class 2606 OID 18142)
-- Name: balance currency_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.balance
    ADD CONSTRAINT currency_id_fk FOREIGN KEY (currency_id) REFERENCES public.currency(id) NOT VALID;


--
-- TOC entry 3491 (class 2606 OID 18183)
-- Name: transaction currency_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT currency_id_fk FOREIGN KEY (currency_id) REFERENCES public.currency(id) NOT VALID;


--
-- TOC entry 3489 (class 2606 OID 18147)
-- Name: balance profile_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.balance
    ADD CONSTRAINT profile_id_fk FOREIGN KEY (profile_id) REFERENCES public.profile(id) NOT VALID;


--
-- TOC entry 3490 (class 2606 OID 18178)
-- Name: transaction profile_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT profile_id_fk FOREIGN KEY (profile_id) REFERENCES public.profile(id) NOT VALID;


--
-- TOC entry 3492 (class 2606 OID 18239)
-- Name: transaction transaction_id_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT transaction_id_fk FOREIGN KEY (transaction_id) REFERENCES public.transaction_name(id) NOT VALID;


-- Completed on 2022-10-04 22:16:32 +04

--
-- PostgreSQL database dump complete
--

